## Team tiers (lower is better)
Amazons:            0
Black Orcs:         3
Chaos Chosen:       3
Chaos Dwarves:      2
Dark Elves:         0
Dwarves:            1
Elven Union:        2
Gnome:              4
Goblins:            4
Halflings:          4
High Elves:         2
Humans:             2
Imperial Nobility:  3
Khorne:             3
Lizardmen:          0
Necromantic:        2
Norse:              1
Nurgle:             3
OWA:                3
Ogre:               4
Orcs:               1
Renegades:          3
Skaven:             0
Slann:              3
Snotlings:          3
Tomb Kings:         2
Undead:             1
Underworld:         2
Vampires:           0
Wood Elves:         1